name:                ParallelBoggle
version:             0.1.0.0
github:              "kkysen/ParallelBoggle"
license:             BSD3
author:              "Khyber Sen"
maintainer:          "kkysen@gmail.com"
copyright:           "Copyright: (C) 2019 Khyber Sen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kkysen/ParallelBoggle#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- bytestring-trie
- containers
- interpolate

library:
  source-dirs: src

executables:
  ParallelBoggle-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ParallelBoggle

tests:
  ParallelBoggle-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ParallelBoggle
